import { Router, type IRouter } from "express";
import healthRouter from "./health/index.js";
import authRouter from "./auth/index.js";
import usersRouter from "./users/index.js";
import classesRouter from "./classes/index.js";
import studentsRouter from "./students/index.js";
import bulkImportRouter from "./students/bulk-import.js";
import attendanceRouter from "./attendance/index.js";
import financeRouter from "./finance/index.js";
import financeExportRouter from "./finance/export.js";
import dashboardRouter from "./dashboard/index.js";
import auditRouter from "./audit/index.js";
import subjectsRouter from "./subjects/index.js";
import examResultsRouter from "./exam-results/index.js";
import timetableRouter from "./timetable/index.js";
import notificationsRouter from "./notifications/index.js";
import calendarRouter from "./calendar/index.js";
import documentsRouter from "./documents/index.js";
import passwordResetRouter from "./password-reset/index.js";
import parentStudentsRouter from "./parent-students/index.js";
import tenantsRouter from "./tenants/index.js";
import hardwareRouter from "./hardware/index.js";
import aiSummaryRouter from "./ai-summary/index.js";
import payrollRouter from "./payroll/index.js";
import reminderSettingsRouter from "./finance/reminder-settings.js";
import discountsRouter from "./finance/discounts.js";
import expensesRouter from "./finance/expenses.js";
import pnlRouter from "./finance/pnl.js";
import budgetsRouter from "./finance/budgets.js";
import feeSchedulesRouter from "./finance/fee-schedules.js";
import collectionReportRouter from "./finance/collection-report.js";
import escalationsRouter from "./finance/escalations.js";
import escalationSettingsRouter from "./finance/escalation-settings.js";
import parentFeeStatementRouter from "./parent/fee-statement.js";
import parentPaymentRequestsRouter from "./parent/payment-requests.js";
import healthAnalyticsRouter from "./finance/health-analytics.js";
import statementActivityRouter from "./finance/statement-activity.js";
import statementScheduleRouter from "./finance/statement-schedule.js";
import studentRouter from "./student/index.js";
import studentNotesRouter from "./student-notes/index.js";
import studentIncidentsRouter from "./student-incidents/index.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(tenantsRouter);
router.use(usersRouter);
router.use(classesRouter);
router.use(studentsRouter);
router.use(bulkImportRouter);
router.use(attendanceRouter);
router.use(financeRouter);
router.use(financeExportRouter);
router.use(dashboardRouter);
router.use(auditRouter);
router.use(subjectsRouter);
router.use(examResultsRouter);
router.use(timetableRouter);
router.use(notificationsRouter);
router.use(calendarRouter);
router.use(documentsRouter);
router.use(passwordResetRouter);
router.use(parentStudentsRouter);
router.use(hardwareRouter);
router.use(aiSummaryRouter);
router.use(payrollRouter);
router.use(reminderSettingsRouter);
router.use(discountsRouter);
router.use(expensesRouter);
router.use(pnlRouter);
router.use(budgetsRouter);
router.use(feeSchedulesRouter);
router.use(collectionReportRouter);
router.use(escalationsRouter);
router.use(escalationSettingsRouter);
router.use(parentFeeStatementRouter);
router.use(parentPaymentRequestsRouter);
router.use(healthAnalyticsRouter);
router.use(statementActivityRouter);
router.use(statementScheduleRouter);
router.use(studentRouter);
router.use(studentNotesRouter);
router.use(studentIncidentsRouter);

export default router;
